version: '3.4'
services:
  wordpress:
    env_file: default.env
    build:
      context: ./wordpress
      args:
        WP_VERSION: ${WP_VERSION}
    image: ${REGISTRY_HOST}/${REGISTRY_PREFIX}/wordpress:${WP_VERSION}
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_PASSWORD=password
    ports:
      - 8080:80
    healthcheck:
      test: curl --fail -s http://localhost:80/ || exit 1
      start_period: 40s
      interval: 30s
      timeout: 10s
      retries: 3

  mariadb:
    env_file: default.env
    build:
      context: ./mariadb
      args:
        MARIA_VERSION: ${MARIA_VERSION}
    image: ${REGISTRY_HOST}/${REGISTRY_PREFIX}/mariadb:${MARIA_VERSION} 
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
