version: '3.4'
services:
  wordpress:
    env_file: default.env
    build:
      context: ./wordpress
      args:
        WP_VERSION: ${WP_VERSION}
    image: ${REGISTRY_HOST}/${REGISTRY_PREFIX}/wordpress:${WP_VERSION}
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_PASSWORD=password
    ports:
      - 80:80

  mariadb:
    env_file: default.env
    build:
      context: ./mariadb
      args:
        MARIA_VERSION: ${MARIA_VERSION}
    image: ${REGISTRY_HOST}/${REGISTRY_PREFIX}/mariadb:${MARIA_VERSION} 
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
