version: '3.4'
services:
  wordpress:
    image: ECR_WORDPRESS_IMAGE 
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_PASSWORD=password
    ports:
      - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-group: wordpress
        awslogs-region: us-east-1
        awslogs-stream-prefix: wordpress

  mariadb:
    image: ECR_MARIADB_IMAGE 
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    logging:
      driver: awslogs
      options:
        awslogs-group: mariadb
        awslogs-region: us-east-1
        awslogs-stream-prefix: mariadb
