version: '3.4'
services:
  wordpress:
    env_file: default.env
    build:
      context: ./wordpress
      args:
        WP_VERSION: ${WP_VERSION}
    image: ${REGISTRY_HOST}/${REGISTRY_PREFIX}/wordpress:${WP_VERSION}
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_PASSWORD=password
    ports:
      - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-group: wordpress
        awslogs-region: us-east-1
        awslogs-stream-prefix: wordpress

  mariadb:
    env_file: default.env
    build:
      context: ./mariadb
      args:
        MARIA_VERSION: ${MARIA_VERSION}
    image: ${REGISTRY_HOST}/${REGISTRY_PREFIX}/mariadb:${MARIA_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    logging:
      driver: awslogs
      options:
        awslogs-group: mariadb
        awslogs-region: us-east-1
        awslogs-stream-prefix: mariadb
